//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps.module.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_data_adjust
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string p_title { get; set; }
        public string p_college { get; set; }
        public string p_major { get; set; }
        public string p_learnStyle { get; set; }
        public Nullable<int> p_enrolment { get; set; }
        public Nullable<System.DateTime> p_releaseTime { get; set; }
        public Nullable<System.DateTime> p_contactMode { get; set; }
        public string p_content { get; set; }
        public string p_spare { get; set; }
        public string IsDeleted { get; set; }
    }
}
