//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps.module.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_sys_user
    {
        public System.Guid Id { get; set; }
        public string avatarUrl { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string gender { get; set; }
        public string lang { get; set; }
        public string nickName { get; set; }
        public string province { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string IsDeleted { get; set; }
    }
}
